server:
  address: 0.0.0.0
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3308/user_db?createDatabaseIfNotExist=true
    username: root
    password: 123456@Ab
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
